Developer/src/objects/AWS__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>AccessKeyId__c</fullName>
        <defaultValue>&quot;----- DUMMY -----&quot;</defaultValue>
        <label>AccessKeyId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <defaultValue>&quot;----- DUMMY -----&quot;</defaultValue>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SecretAccessKey__c</fullName>
        <defaultValue>&quot;----- DUMMY -----&quot;</defaultValue>
        <label>SecretAccessKey</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>AWS</label>
</CustomObject>

Developer/src/classes/DynamoDBClientTest.cls
@isTest
private class DynamoDBClientTest {

    static testMethod void putItem(){
        AWS__c a = new AWS__c();
        a.AccessKeyId__c = 'test';
        a.Region__c= 'test';
        a.SecretAccessKey__c= 'test';
        insert a;
        
        System.assertEquals('test', AWS__c.getOrgDefaults().SecretAccessKey__c);
    
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockImpl());
        DynamoDBClient cl = new DynamoDBClient();
        
        Test.startTest();
        cl.putItem('');
        Test.stopTest();
    }
}