Developer/src/objects/Campaign__c.object
<CustomObject>
    <label>キャンペーン</label>
    <nameField>
        <label>キャンペーン名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Developer/src/objects/Constants__c.object
<CustomObject>
    <fields>
        <fullName>Key1__c</fullName>
        <label>Key1</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key2__c</fullName>
        <label>Key2</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Constants</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Constants名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Developer/src/classes/ConstantsDao.cls
/*
@Name            : ConstantsDao
@Author          : Satoshi Haga
@Description     : Data Access Class for Campaign__c
@version         : First Create 2013/12/11 Satoshi Haga
*/
public with sharing class ConstantsDao extends BaseDao{

  /**
   * ConstantsDao
   */
  public ConstantsDao(){
    super(new Constants__c().getSObjectType());
  }

  /** Get ID of specific object */
  public ID getIdByKeyStrings(String key1, String key2){

  	String pKey1 = key1;
  	String pKey2 = key2;

  	String strSOQL = 'SELECT Id, Value__c FROM ' + getObjectName() + ' WHERE Key1__c = :pKey1 AND Key2__c = :pKey2';

  	List<Constants__c> listConst = (List<Constants__c>)database.query(strSOQL);

  	//Invalid Key
  	if(listConst == null || listConst.size() == 0){
  		return null;
  	}

  	//Convert from string to ID
  	ID ret = (ID)listConst.get(0).Value__c;

  	//Return
  	return ret;
  }

}