Developer/src/objects/Campaign__c.object
<CustomObject>
    <label>キャンペーン</label>
    <nameField>
        <label>キャンペーン名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Developer/src/objects/CampaignGoods__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>対象キャンペーン</label>
        <referenceTo>Campaign__c</referenceTo>
        <relationshipLabel>キャンペーン商品</relationshipLabel>
        <relationshipName>RelatedCampaigns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>キャンペーン商品</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>キャンペーン商品名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Developer/src/classes/CampaignGoodsDao.cls
/*
@Name            : CampaignGoodsDao
@Author          : Satoshi Haga
@Description     : Data Access Class for CampaignGoods__c
@version         : First Create 2013/12/11 Satoshi Haga
*/
public with sharing class CampaignGoodsDao extends BaseDao{

  /**
   * Constructor
   */
  public CampaignGoodsDao(){
    super(new CampaignGoods__c().getSObjectType());
  }

  	/** Get id list of related goods*/
	public List<CampaignGoods__c> getRelatedGoods(ID campaignId){

		//Create soql string
		ID pId = campaignId;
		String strQuery = 'SELECT ' + getAllColumnString() + ' FROM ' + getObjectName() + ' WHERE Campaign__c = :pId';

		//Execute SOQL
		List<CampaignGoods__c> listCampaignGoods = (List<CampaignGoods__c>)database.query(strQuery);

		if(listCampaignGoods == null || listCampaignGoods.size() == 0){
			//Invalid Id
			return null;
		}

		//Return
		return listCampaignGoods;
	}

}