Developer/src/objects/DistrictMaster__c.object
<CustomObject>
    <fields>
        <fullName>ZipCode__c</fullName>
        <label>郵便番号(7桁)</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <label>地域マスタ</label>
    <nameField>
        <label>全国地方公共団体コード</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Developer/src/objects/PurchaseTransaction__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>売価</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PuchaseDate__c</fullName>
        <label>購買年月日</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PuchasedBy__c</fullName>
        <label>購買者</label>
        <referenceTo>UserInformation__c</referenceTo>
        <relationshipLabel>購買履歴</relationshipLabel>
        <relationshipName>PuchasedBy</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PurchaseType__c</fullName>
        <label>取引種別</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>購買履歴</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>購買トランザクション名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Developer/src/objects/UserInformation__c.object
<CustomObject>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>所属地域</label>
        <referenceTo>DistrictMaster__c</referenceTo>
        <relationshipLabel>ユーザー情報</relationshipLabel>
        <relationshipName>District</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <label>郵便番号</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <label>ユーザー情報</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Developer/src/classes/UserInformationTriggerHandler.cls
/*
@Name            : UserInformationTriggerHandler
@Author          : Satoshi Haga
@Description     : Trigger executtion class. This class assign appropriate district to user.
@version         : First Create 2013/12/11 Satoshi Haga
*/
public class UserInformationTriggerHandler{


	/**
	 * Trigger execution method. This is triggered before insertion.
	 * @param newReqs the list of new record
	 */
	public void OnBeforeInsert(UserInformation__c[] newReqs){

		//Synchronize district with zip-code
		for(UserInformation__c userInfo : newReqs){
			//Set appropriate district to each user information record.
			if(userInfo.ZipCode__c != null && !''.equals(userInfo.ZipCode__c)){
				DistrictDao dao = new DistrictDao();
				DistrictMaster__c district = dao.getDistrict(userInfo.ZipCode__c);

				//When inappropriate zip-code, skip this record.
				if(district == null){
					continue;
				}

				//Set district to this record
				userInfo.District__c = district.Id;
			}
		}

		//Insert initial cost into PurchaseTransaction__c
		PurchaseTransaction__c purchase = new PurchaseTransaction__c();

		purchase.PuchasedBy__c = new UserInformationDao().getRelatedRecord(UserInfo.getUserId()).Id;
		purchase.PuchaseDate__c = date.today();
		purchase.Price__c = CommonConstants.PRICE_INITIAL_COST;
		purchase.PurchaseType__c = CommonConstants.INITIAL_COST;

		//Add it into database.
		insert purchase;

	}

	/**
	 * Trigger execution method. This is triggered before updation.
	 * @param old the list of old record
	 * @param updated the list of new record
	 * @param triggerMap the mapping file of new record
	 */
	public void OnBeforeUpdate(UserInformation__c[] old, UserInformation__c[] updated, Map<ID, UserInformation__c> triggerMap){


		for(UserInformation__c oldUser : old){
			for(UserInformation__c newUser : updated){

				//Re-assign district only when zip-code is changed.
				if(oldUser.Id == newUser.Id
					&& newUser.ZipCode__c != null && !newUser.ZipCode__c.equals(oldUser.ZipCode__c)){

						//Get district data by new zip code
						DistrictDao dao = new DistrictDao();
						DistrictMaster__c district = dao.getDistrict(newUser.ZipCode__c);

						//When inappropriate zip-code, skip this record.
						if(district == null){
							continue;
						}

						//Set district to this record
						newUser.District__c = district.Id;
				}
			}
		}
	}


}