Developer/src/objects/FriendRequest__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalFlg__c</fullName>
        <label>承認状況</label>
        <picklist>
            <picklistValues>
                <fullName>承認</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>拒否</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RelatedUserInformation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>被申請者</label>
        <referenceTo>UserInformation__c</referenceTo>
        <relationshipLabel>フレンドリクエスト</relationshipLabel>
        <relationshipName>RelatedUserInformation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestedTime__c</fullName>
        <label>申請時間</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>RequestingUserInformation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>申請者</label>
        <referenceTo>UserInformation__c</referenceTo>
        <relationshipLabel>フレンドリクエスト (申請者)</relationshipLabel>
        <relationshipName>RequestingUserInformation</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>フレンドリクエスト</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>フレンドリクエスト名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Developer/src/classes/FriendRequestDao.cls
/*
@Name            : FriendRequestDao
@Author          : Satoshi Haga
@Description     : Data Access Class for FriendRequest__c
@version         : First Create 2013/12/11 Satoshi Haga
*/
public with sharing class FriendRequestDao extends BaseDao{

  /**
   * Constructor
   */
  public FriendRequestDao(){
    super(new FriendRequest__c().getSObjectType());
  }


	/** Get non-approved list of friends */
	public List<FriendRequest__c> getNonApprovedList(Id userId){

		ID pId = userId;

		//Create SOQL string
		String strQuery = 'SELECT ' + getAllColumnString() + ' FROM ' + getObjectName() + ' ';
		strQuery += 'WHERE ApprovalFlg__c = \'\' AND RelatedUserInformation__c = :pId';

		//Execute
		List<FriendRequest__c> ret = database.query(strQuery);

		//If there is not non-approved list, return empty list
		if(ret == null || ret.size() == 0){
			return new List<FriendRequest__c>();
		}

		//Return
		return ret;
	}

	/** Get Latest Status */
	public FriendRequest__c getLatestStatus(ID userID, ID friendID){

		//Initialize member variable
		ID pUserID = userID;
		ID pFriendID = friendID;

		//Create SOQL string
		String strQuery = 'SELECT ' + getAllColumnString() + ' FROM ' + getObjectName() + ' ';
		strQuery += ' WHERE ApprovalFlg__c <> \'拒否\'';
		strQuery += ' AND RequestingUserInformation__c = :pUserID ';
		strQuery += ' AND RelatedUserInformation__c = :pFriendID ';
		strQuery += ' ORDER BY RequestedTime__c DESC LIMIT 1 ';

		//Execute
		List<FriendRequest__c> ret = database.query(strQuery);

		//If there is not non-approved list, return null value
		if(ret == null || ret.size() == 0){

			return null;

		}

		//Return
		return ret.get(0);
	}


}