Developer/src/objects/FriendRequest__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalFlg__c</fullName>
        <label>承認状況</label>
        <picklist>
            <picklistValues>
                <fullName>承認</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>拒否</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RelatedUserInformation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>被申請者</label>
        <referenceTo>UserInformation__c</referenceTo>
        <relationshipLabel>フレンドリクエスト</relationshipLabel>
        <relationshipName>RelatedUserInformation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestedTime__c</fullName>
        <label>申請時間</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>RequestedUserLookUp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>被申請者(User)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RequestedUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestingUserInformation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>申請者</label>
        <referenceTo>UserInformation__c</referenceTo>
        <relationshipLabel>フレンドリクエスト (申請者)</relationshipLabel>
        <relationshipName>RequestingUserInformation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestingUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>申請者(User)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RequestingUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>フレンドリクエスト</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>フレンドリクエスト名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Developer/src/objects/UserInformation__c.object
<CustomObject>
    <fields>
        <fullName>CheckStatus__c</fullName>
        <defaultValue>false</defaultValue>
        <label>選択ステータス</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DistrictName__c</fullName>
        <formula>District__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>全国地方公共団体コード</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FriendStatus__c</fullName>
        <label>友達ステータス</label>
        <picklist>
            <picklistValues>
                <fullName>友達申請中です</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>既にお友達です</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RelatedUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>対象ユーザー</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RelatedUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ユーザー情報</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Developer/src/objects/UserInformationCriteria__c.object
<CustomObject>
    <fields>
        <fullName>DistrictName__c</fullName>
        <label>地域名（検索用）</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>ユーザー情報検索条件</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>ユーザー情報検索条件名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Developer/src/classes/FriendSearchController.cls
/*
@Name            : FriendSearchController
@Author          : Satoshi Haga
@Description     : Controller class for Friend Search Function
@version         : First Create 2013/12/11 Satoshi Haga
*/
public   class FriendSearchController extends BaseController {


	/** Search Criteria */
	public UserInformationCriteria__c criteria{get; set;}

	/** Searching result */
	public List<UserInformation__c> listUser{get; set;}

	/** Constructor */
	public FriendSearchController(){

		super();

		listUser = new List<UserInformation__c>();

		//Initialize criteria
		criteria = new UserInformationCriteria__c();

		//Set user's district to the criteria
		criteria.DistrictName__c = loginUsaerInfo.DistrictName__c;

	}

	/** Searching Method */
	public void search(){

		FriendRequestDao friDao = new FriendRequestDao();

		listUser = new UserInformationDao().getListDataByCriteria(criteria);

		//If there is no data, return here
		if(listUser == null || listUser.size() == 0){
			listUser = new List<UserInformation__c>();
			return ;
		}


		List<UserInformation__c> ret = new List<UserInformation__c>();
		for(UserInformation__c user : listUser){

			//exclude my record
			if(loginUsaerInfo.Id != user.Id){
				ret.add(user);
			}

			//Check current status
			FriendRequest__c latestReq = friDao.getLatestStatus(loginUsaerInfo.Id, user.Id);

			if(latestReq != null){
				if(latestReq.ApprovalFlg__c == null || ''.equals(latestReq.ApprovalFlg__c)){
					//Not commited yet
					user.FriendStatus__c = '友達申請中です';
				}

				if('承認'.equals(latestReq.ApprovalFlg__c)){
					//Already commited
					user.FriendStatus__c = '既にお友達です';
				}
			}
		}

		//Re-asign member list
		listUser = ret;
	}


	/** Send Friend Request */
	public void submitRequest(){

		List<FriendRequest__c> listRequest = new List<FriendRequest__c>();

		//For each selected-user record, create request record.
		//Then request-email is sent by workflow rule
		for( UserInformation__c requestedUser : listUser){

			if(requestedUser.CheckStatus__c == true){
				//Create each request instance, and add this into the list.
				FriendRequest__c req = new FriendRequest__c();

				req.RequestingUserInformation__c = loginUsaerInfo.Id;
				req.RequestingUser__c = loginUsaerId;
				req.RelatedUserInformation__c = requestedUser.Id;
				req.RequestedUserLookUp__c = requestedUser.RelatedUser__c;
				req.RequestedTime__c = System.now();


				listRequest.add(req);
			}
		}

		//Bulk-insert
		if(listRequest.size() > 0){
			insert listRequest;
		}

		//Refresh friend list by calling serch method
		search();

		//Add Success Message
		ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, CommonConstants.SUCCESS_SUBMIT_FRIEND_REQUEST, ''));
	}


}