Developer/src/objects/Goods__c.object
<CustomObject>
    <fields>
        <fullName>CheckStatus__c</fullName>
        <defaultValue>false</defaultValue>
        <label>チェックステータス</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PurchaseAmount__c</fullName>
        <label>購入個数</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PurchaseTransaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>購買履歴</label>
        <referenceTo>PurchaseTransaction__c</referenceTo>
        <relationshipLabel>販売商品</relationshipLabel>
        <relationshipName>PurchaseRelation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StandardPrice__c</fullName>
        <label>標準価格</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>販売商品</label>
    <nameField>
        <label>販売商品名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Developer/src/objects/GoodsCriteria__c.object
<CustomObject>
    <label>販売商品検索条件</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>販売商品検索条件名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Developer/src/objects/PurchaseTransaction__c.object
<CustomObject>
    <fields>
        <fullName>Goods__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>販売商品</label>
        <referenceTo>Goods__c</referenceTo>
        <relationshipLabel>購買履歴</relationshipLabel>
        <relationshipName>GoodsRelation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>売価</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PuchaseDate__c</fullName>
        <label>購買年月日</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PuchasedBy__c</fullName>
        <label>購買者</label>
        <referenceTo>UserInformation__c</referenceTo>
        <relationshipLabel>購買履歴</relationshipLabel>
        <relationshipName>PuchasedBy</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PurchaseAmount__c</fullName>
        <formula>PurchaseNumber__c  *  Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>購入金額</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PurchaseNumber__c</fullName>
        <label>購入個数</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PurchaseType__c</fullName>
        <label>取引種別</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>購買履歴</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>購買トランザクション名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Developer/src/classes/GoodsSearchController.cls
/*
@Name            : GoodsSearchController
@Author          : Satoshi Haga
@Description     : Controller class for Goods Search Function
@version         : First Create 2013/12/11 Satoshi Haga
*/
public   class GoodsSearchController extends BaseController {


	/** Search Criteria */
	public GoodsCriteria__c criteria{get; set;}

	/** Searching result */
	public List<Goods__c> listGoods{get; set;}

	/** Constructor */
	public GoodsSearchController(){

		super();

		listGoods = new List<Goods__c>();

		//Initialize criteria
		criteria = new GoodsCriteria__c();

	}

	/** Searching Method */
	public void search(){
		listGoods = new GoodsDao().getListDataByCriteria(criteria);

		//
	}

	/** Purchaing Method */
	public void purchaseOrder(){

		List<PurchaseTransaction__c> listPurchase = new List<PurchaseTransaction__c>();

		//For each selected-goods record, create purchase-order record.
		for( Goods__c goods : listGoods){

			if(goods.CheckStatus__c == true){
				//Create each purchase instance, and add this into the list.
				PurchaseTransaction__c req = new PurchaseTransaction__c();

				req.Goods__c = goods.Id;
				req.PuchasedBy__c = loginUsaerInfo.Id;
				req.PuchaseDate__c = date.today();
				req.PurchaseNumber__c = goods.PurchaseAmount__c;
				req.Price__c = goods.StandardPrice__c;
				req.PurchaseType__c = CommonConstants.NORMAL_PURCHASE;

				listPurchase.add(req);
			}
		}

		//Bulk-insert
		if(listPurchase.size() > 0){
			insert listPurchase;
		}

		//Refresh friend list by calling serch method
		search();

		//Add Success Message
		ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, CommonConstants.SUCCESS_SUBMIT_FIHISH_TRANSACTION, ''));

	}

}