Developer/src/objects/Goods__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>カテゴリ</label>
        <picklist>
            <picklistValues>
                <fullName>01:ｳｪｯﾄﾃｨｯｼｭ（赤ちゃん用）</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02:ｴｱﾌﾚｯｼｭﾅｰ　ﾄｲﾚ用</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03:おむつ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04:ｼｬﾝﾌﾟｰ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05:ﾄﾘｰﾄﾒﾝﾄ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06:液体用洗剤</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07:柔軟剤</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>v8:食器用洗剤</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09:対面販売化粧品</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:電動歯ﾌﾞﾗｼ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StandardPrice__c</fullName>
        <label>標準価格</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>販売開始年月日</label>
        <type>Date</type>
    </fields>
    <label>販売商品</label>
    <nameField>
        <label>販売商品名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Developer/src/objects/GoodsCriteria__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>カテゴリ</label>
        <picklist>
            <picklistValues>
                <fullName>ｳｪｯﾄﾃｨｯｼュ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ｴｱﾌﾚｯｼｭﾅｰ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>おむつ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ｼｬﾝﾌﾟｰ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ﾄﾘｰﾄﾒﾝﾄ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>液体用洗剤</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>柔軟剤</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>食器用洗剤</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>対面販売化粧品</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>電動歯ﾌﾞﾗｼ</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>PriceFrom__c</fullName>
        <label>標準価格(From)</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PriceTo__c</fullName>
        <label>標準価格(To)</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>～以降に販売された商品</label>
        <type>Date</type>
    </fields>
    <label>販売商品検索条件</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>販売商品検索条件名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Developer/src/classes/GoodsDao.cls
/*
@Name            : GoodsDao
@Author          : Satoshi Haga
@Description     : Data Access Class for Goods__c
@version         : First Create 2013/12/11 Satoshi Haga
*/
public class GoodsDao extends BaseDao{


  /**
   * Constructor
   */
  public GoodsDao(){
    super(new Goods__c().getSObjectType());
  }

  /** Get list by criteria */
  public List<Goods__c> getListDataByCriteria(GoodsCriteria__c criteria){

  	//Declare member variables in order to use these in SOQL as binded variables
  	List<String> strCategoryList = CommonUtil.convertMultiPick(criteria.Category__c);
  	Decimal fromPrice = criteria.PriceFrom__c;
  	Decimal toPrice = criteria.PriceTo__c;
  	Date fromDate = criteria.StartDate__c;

  	//Create Query String
  	String strQuery = 'SELECT ' + getAllColumnString() + ' FROM ' + getObjectName() + ' ';
  	String strJoin = ' WHERE ';

  	if(strCategoryList != null && strCategoryList.size() > 0){
  		strQuery += strJoin + ' Category__c IN :strCategoryList ';
  		strJoin = ' AND ';
  	}

	if(fromPrice != null){
  		strQuery += strJoin + ' StandardPrice__c >= :fromPrice ';
  		strJoin = ' AND ';
	}

	if(toPrice != null){
  		strQuery += strJoin + ' StandardPrice__c <= :toPrice ';
  		strJoin = ' AND ';
	}

	if(fromDate != null){
  		strQuery += strJoin + ' StartDate__c >= :fromDate ';
  		strJoin = ' AND ';
	}

	//Execute SOQL
  	List<Goods__c> result = new List<Goods__c>();
  	for(Goods__c rec :  (List<Goods__c>)database.query(strQuery)){
  		result.add(rec);
  	}

	//If there is no data, return null value;
	if(result == null || result.size() == 0){
		return null;
	}

	//Return
	return result;

  }
}