Developer/src/objects/UserInformation__c.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <formula>IF(OR(MONTH(today())-MONTH(BirthDay__c)&gt;0,AND(MONTH(TODAY()) - MONTH(BirthDay__c)&gt;=0,DAY(TODAY()) - DAY(BirthDay__c)&gt;=0)),
YEAR(TODAY()) - YEAR(BirthDay__c),
YEAR(TODAY()) - YEAR(BirthDay__c)-1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>年齢</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ChildCount__c</fullName>
        <label>子供の人数</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DistrictName__c</fullName>
        <formula>District__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>全国地方公共団体コード</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JobStatus__c</fullName>
        <label>職業</label>
        <picklist>
            <picklistValues>
                <fullName>無職</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>無職(定年)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>無職(主婦)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>アルバイト</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>パート</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>自営業</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>会社員</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Marriage__c</fullName>
        <label>婚姻状態</label>
        <picklist>
            <picklistValues>
                <fullName>未婚</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>既婚</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RelatedUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>対象ユーザー</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RelatedUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <label>性別</label>
        <picklist>
            <picklistValues>
                <fullName>男性</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>女性</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>ユーザー情報</label>
    <nameField>
        <label>氏名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Developer/src/objects/UserInformationCriteria__c.object
<CustomObject>
    <fields>
        <fullName>AgeFrom__c</fullName>
        <label>年齢(From)</label>
        <picklist>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>31</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>33</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>34</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>35</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>36</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>37</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>38</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>39</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>41</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>43</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>44</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>45</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>46</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>47</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>48</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>49</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AgeTo__c</fullName>
        <label>年齢(To)</label>
        <picklist>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>31</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>33</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>34</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>35</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>36</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>37</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>38</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>39</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>41</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>43</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>44</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>45</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>46</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>47</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>48</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>49</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DistrictName__c</fullName>
        <label>地域名（検索用）</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HasChildrenList__c</fullName>
        <label>子供</label>
        <picklist>
            <picklistValues>
                <fullName>いる</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>いない</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>JobStatusList__c</fullName>
        <label>職業</label>
        <picklist>
            <picklistValues>
                <fullName>無職</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>無職(定年)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>無職(主婦)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>アルバイト</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>パート</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>自営業</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>会社員</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Marriage__c</fullName>
        <label>婚姻状態</label>
        <picklist>
            <picklistValues>
                <fullName>既婚</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>未婚</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <label>性別</label>
        <picklist>
            <picklistValues>
                <fullName>男性</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>女性</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>ユーザー情報検索条件</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>ユーザー情報検索条件名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Developer/src/classes/UserInformationDao.cls
/*
@Name            : UserInformationDao
@Author          : Satoshi Haga
@Description     : Data Access Class for UserInformation__c
@version         : First Create 2013/12/11 Satoshi Haga
*/

public class UserInformationDao extends BaseDao{


  /**
   * Constructor
   */
  public UserInformationDao(){
    super(new UserInformation__c().getSObjectType());
  }

  /** Get one record related with parametered id */
  public UserInformation__c getRelatedRecord(Id pId){
	Map<String, String> param1 = new Map<String, String>();
	param1.put('RelatedUser__c', (String)pId);


	List<UserInformation__c> listUser = (List<UserInformation__c>)getValue(param1);

	if(listUser == null || listUser.size() == 0) {
		//Invalid user id
		return null;
	}

	//Return
	return listUser.get(0);
  }

  /** Get list by criteria */
  public List<UserInformation__c> getListDataByCriteria(UserInformationCriteria__c criteria){

  	//If criteria doesn't have dstrict-value becuase of some reason, return here with no value
  	if(criteria.DistrictName__c == null){
  		return null;
  	}
  	String pDistrictName = criteria.DistrictName__c;

  	//Declare member variables in order to use these in SOQL as binded variables
  	List<String> strJobList = CommonUtil.convertMultiPick(criteria.JobStatusList__c);
  	Integer fromAge ;
  	Integer toAge ;
	String strMarrige = criteria.Marriage__c;
	String strSex = criteria.Sex__c;
	Boolean hasChild;

	If('いる'.equals(criteria.HasChildrenList__c)){
		hasChild = true;
	}

	If('いない'.equals(criteria.HasChildrenList__c)){
		hasChild = false;
	}

  	//Create Query String
  	String strQuery = 'SELECT ' + getAllColumnString() + ' FROM ' + getObjectName() + ' ';
  	String strJoin = ' WHERE ';

  	if(strJobList != null && strJobList.size() > 0){
  		strQuery += strJoin + ' JobStatus__c IN :strJobList ';
  		strJoin = ' AND ';
  	}

	if(criteria.AgeFrom__c != null && !''.equals(criteria.AgeFrom__c)){
		fromAge = Integer.valueOf(criteria.AgeFrom__c);
  		strQuery += strJoin + ' Age__c >= :fromAge ';
  		strJoin = ' AND ';
	}

	if(criteria.AgeTo__c != null && !''.equals(criteria.AgeTo__c)){
		toAge = Integer.valueOf(criteria.AgeTo__c);
  		strQuery += strJoin + ' Age__c <= :toAge ';
  		strJoin = ' AND ';
	}

	if(strMarrige != null && !''.equals(strMarrige)){
  		strQuery += strJoin + ' Marriage__c = :strMarrige ';
  		strJoin = ' AND ';
	}

	if(strSex != null && !''.equals(strSex)){
  		strQuery += strJoin + ' Sex__c = :strSex ';
  		strJoin = ' AND ';
	}


	if(hasChild == true){
  		strQuery += strJoin + ' ChildCount__c > 0 ';
  		strJoin = ' AND ';
	}

	if(hasChild == false){
  		strQuery += strJoin + ' ChildCount__c = 0 ';
  		strJoin = ' AND ';
	}

	//District
  	strQuery += strJoin + ' DistrictName__c = :pDistrictName ';
  	strJoin = ' AND ';


	//Upper limit
	strQuery += ' LIMIT ' + CommonConstants.UPPER_LIMIT_COUNT;

	//Execute SOQL
  	List<UserInformation__c> result = new List<UserInformation__c>();
  	for(UserInformation__c rec :  (List<UserInformation__c>)database.query(strQuery)){
  		result.add(rec);
  	}

	//If there is no data, return null value;
	if(result == null || result.size() == 0){
		return null;
	}

	//Return
	return result;

  }


}